// Auto generated by Craby. DO NOT EDIT.
#include <CxxCalculatorModule.hpp>
#include <CxxCrabyTestModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabytest::modules::CxxCalculatorModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabytest::modules::CxxCalculatorModule>(jsInvoker);
    });
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabytest::modules::CxxCrabyTestModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabytest::modules::CxxCrabyTestModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_rs_craby_crabytest_CrabyTestPackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  const char* cDataPath = env->GetStringUTFChars(jDataPath, nullptr);
  auto dataPath = std::string(cDataPath);
  env->ReleaseStringUTFChars(jDataPath, cDataPath);
  craby::crabytest::modules::CxxCalculatorModule::dataPath = dataPath;
  craby::crabytest::modules::CxxCrabyTestModule::dataPath = dataPath;
}
