// Auto generated by Craby. DO NOT EDIT.
// Hash:
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait {{ pascal_name }}Spec {
    fn new(id: usize) -> Self;
    fn id(&self) -> usize;
}
