// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::craby_test_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::bridging")]
pub mod bridging {
    // Type definitions
    struct NullableNumber {
        null: bool,
        val: f64,
    }

    struct NullableString {
        null: bool,
        val: String
    }

    struct SubObject {
        a: NullableString,
        b: f64,
        c: bool,
    }

    struct NullableSubObject {
        null: bool,
        val: SubObject
    }

    struct TestObject {
        foo: String,
        bar: f64,
        baz: bool,
        sub: NullableSubObject,
    }

    enum MyEnum {
        FOO,
        BAR,
        BAZ,
    }

    extern "Rust" {
        #[cxx_name = "numericMethod"]
        fn craby_test_numeric_method(arg: f64) -> f64;

        #[cxx_name = "booleanMethod"]
        fn craby_test_boolean_method(arg: bool) -> bool;

        #[cxx_name = "stringMethod"]
        fn craby_test_string_method(arg: String) -> String;

        #[cxx_name = "objectMethod"]
        fn craby_test_object_method(arg: TestObject) -> TestObject;

        #[cxx_name = "arrayMethod"]
        fn craby_test_array_method(arg: Vec<f64>) -> Vec<f64>;

        #[cxx_name = "enumMethod"]
        fn craby_test_enum_method(arg: MyEnum) -> String;

        #[cxx_name = "nullableMethod"]
        fn craby_test_nullable_method(arg: NullableNumber) -> NullableNumber;

        #[cxx_name = "promiseMethod"]
        fn craby_test_promise_method(arg: f64) -> Result<f64>;
    }
}

fn craby_test_numeric_method(arg: f64) -> f64 {
    let ret = CrabyTest::numeric_method(arg);
    ret
}

fn craby_test_boolean_method(arg: bool) -> bool {
    let ret = CrabyTest::boolean_method(arg);
    ret
}

fn craby_test_string_method(arg: String) -> String {
    let ret = CrabyTest::string_method(arg);
    ret
}

fn craby_test_object_method(arg: TestObject) -> TestObject {
    let ret = CrabyTest::object_method(arg);
    ret
}

fn craby_test_array_method(arg: Vec<f64>) -> Vec<f64> {
    let ret = CrabyTest::array_method(arg);
    ret
}

fn craby_test_enum_method(arg: MyEnum) -> String {
    let ret = CrabyTest::enum_method(arg);
    ret
}

fn craby_test_nullable_method(arg: NullableNumber) -> NullableNumber {
    let ret = CrabyTest::nullable_method(arg.into());
    ret.into()
}

fn craby_test_promise_method(arg: f64) -> Result<f64, anyhow::Error> {
    let ret = CrabyTest::promise_method(arg);
    ret
}
