// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <react/bridging/Bridging.h>
#include "cxx.h"
#include "ffi.rs.h"

using namespace facebook;

namespace facebook {
namespace react {

template <>
struct Bridging<rust::String> {
  static rust::String fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::String(str);
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::String& value) {
    return react::bridging::toJs(rt, std::string(value));
  }
};

template <typename T>
struct Bridging<rust::Vec<T>> {
  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> vec;
    vec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto element = arr.getValueAtIndex(rt, i);
      vec.push_back(react::bridging::fromJs<T>(rt, element, callInvoker));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto jsElement = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, jsElement);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::bridging::MyEnum> {
  static craby::bridging::MyEnum fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto raw = value.asString(rt).utf8(rt);
    if (raw == "FOO") {
      return craby::bridging::MyEnum::FOO;
    } else if (raw == "BAR") {
      return craby::bridging::MyEnum::BAR;
    } else if (raw == "BAZ") {
      return craby::bridging::MyEnum::BAZ;
    } else {
      throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::MyEnum value) {
    switch (value) {
      case craby::bridging::MyEnum::FOO:
        return react::bridging::toJs(rt, "FOO");
      case craby::bridging::MyEnum::BAR:
        return react::bridging::toJs(rt, "BAR");
      case craby::bridging::MyEnum::BAZ:
        return react::bridging::toJs(rt, "BAZ");
      default:
        throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }
};

template <>
struct Bridging<craby::bridging::NullableString> {
  static craby::bridging::NullableString fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    if (value.isNull()) {
      return craby::bridging::NullableString{true, rust::String()};
    }

    auto val = react::bridging::fromJs<rust::String>(rt, value, callInvoker);
    auto ret = craby::bridging::NullableString{false, val};

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::NullableString value) {
    if (value.null) {
      return jsi::Value::null();
    }

    return react::bridging::toJs(rt, value.val);
  }
};

template <>
struct Bridging<craby::bridging::SubObject> {
  static craby::bridging::SubObject fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$a = obj.getProperty(rt, "a");
    auto obj$b = obj.getProperty(rt, "b");
    auto obj$c = obj.getProperty(rt, "c");

    auto _obj$a = react::bridging::fromJs<craby::bridging::NullableString>(rt, obj$a, callInvoker);
    auto _obj$b = react::bridging::fromJs<double>(rt, obj$b, callInvoker);
    auto _obj$c = react::bridging::fromJs<bool>(rt, obj$c, callInvoker);

    craby::bridging::SubObject ret = {
      _obj$a,
      _obj$b,
      _obj$c
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::SubObject value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$a = react::bridging::toJs(rt, value.a);
    auto _obj$b = react::bridging::toJs(rt, value.b);
    auto _obj$c = react::bridging::toJs(rt, value.c);

    obj.setProperty(rt, "a", _obj$a);
    obj.setProperty(rt, "b", _obj$b);
    obj.setProperty(rt, "c", _obj$c);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::bridging::NullableSubObject> {
  static craby::bridging::NullableSubObject fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    if (value.isNull()) {
      return craby::bridging::NullableSubObject{true, craby::bridging::SubObject{}};
    }

    auto val = react::bridging::fromJs<craby::bridging::SubObject>(rt, value, callInvoker);
    auto ret = craby::bridging::NullableSubObject{false, val};

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::NullableSubObject value) {
    if (value.null) {
      return jsi::Value::null();
    }

    return react::bridging::toJs(rt, value.val);
  }
};

template <>
struct Bridging<craby::bridging::TestObject> {
  static craby::bridging::TestObject fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$foo = obj.getProperty(rt, "foo");
    auto obj$bar = obj.getProperty(rt, "bar");
    auto obj$baz = obj.getProperty(rt, "baz");
    auto obj$sub = obj.getProperty(rt, "sub");

    auto _obj$foo = react::bridging::fromJs<rust::String>(rt, obj$foo, callInvoker);
    auto _obj$bar = react::bridging::fromJs<double>(rt, obj$bar, callInvoker);
    auto _obj$baz = react::bridging::fromJs<bool>(rt, obj$baz, callInvoker);
    auto _obj$sub = react::bridging::fromJs<craby::bridging::NullableSubObject>(rt, obj$sub, callInvoker);

    craby::bridging::TestObject ret = {
      _obj$foo,
      _obj$bar,
      _obj$baz,
      _obj$sub
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::TestObject value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$foo = react::bridging::toJs(rt, value.foo);
    auto _obj$bar = react::bridging::toJs(rt, value.bar);
    auto _obj$baz = react::bridging::toJs(rt, value.baz);
    auto _obj$sub = react::bridging::toJs(rt, value.sub);

    obj.setProperty(rt, "foo", _obj$foo);
    obj.setProperty(rt, "bar", _obj$bar);
    obj.setProperty(rt, "baz", _obj$baz);
    obj.setProperty(rt, "sub", _obj$sub);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::bridging::NullableNumber> {
  static craby::bridging::NullableNumber fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    if (value.isNull()) {
      return craby::bridging::NullableNumber{true, 0.0};
    }

    auto val = react::bridging::fromJs<double>(rt, value, callInvoker);
    auto ret = craby::bridging::NullableNumber{false, val};

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::bridging::NullableNumber value) {
    if (value.null) {
      return jsi::Value::null();
    }

    return react::bridging::toJs(rt, value.val);
  }
};

} // namespace react
} // namespace facebook
