// Auto generated by Craby. DO NOT EDIT.
#include "CxxCalculatorModule.hpp"

#include "cxx.h"
#include "bridging-generated.hpp"
#include "utils.hpp"

#include <thread>
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace calculator {

CxxCalculatorModule::CxxCalculatorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCalculatorModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::bridging::Calculator>(
    craby::bridging::createCalculator(reinterpret_cast<uintptr_t>(this)).into_raw(),
    [](craby::bridging::Calculator *ptr) { rust::Box<craby::bridging::Calculator>::from_raw(ptr); }
  );

  methodMap_["add"] = MethodMetadata{2, &CxxCalculatorModule::add};
  methodMap_["subtract"] = MethodMetadata{2, &CxxCalculatorModule::subtract};
  methodMap_["multiply"] = MethodMetadata{2, &CxxCalculatorModule::multiply};
  methodMap_["divide"] = MethodMetadata{2, &CxxCalculatorModule::divide};
}

CxxCalculatorModule::~CxxCalculatorModule() {
  // No signals
}

jsi::Value CxxCalculatorModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

} // namespace calculator
} // namespace craby
