// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "ffi.rs.h"

#include <memory>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

namespace craby {
namespace calculator {

class JSI_EXPORT CxxCalculatorModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "Calculator";

  CxxCalculatorModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxCalculatorModule();

  static facebook::jsi::Value
  add(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  subtract(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  multiply(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  divide(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::bridging::Calculator> module_;
};

} // namespace calculator
} // namespace craby
