// Auto generated by Craby. DO NOT EDIT.
#include "CxxCalculatorModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace crabytest {
namespace modules {

std::string CxxCalculatorModule::dataPath = std::string();

CxxCalculatorModule::CxxCalculatorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCalculatorModule::kModuleName, jsInvoker) {
  callInvoker_ = std::move(jsInvoker);
  // No signals
  module_ = std::shared_ptr<craby::crabytest::bridging::Calculator>(
    craby::crabytest::bridging::createCalculator(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::crabytest::bridging::Calculator *ptr) { rust::Box<craby::crabytest::bridging::Calculator>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::crabytest::utils::ThreadPool>(10);
  methodMap_["add"] = MethodMetadata{2, &CxxCalculatorModule::add};
  methodMap_["divide"] = MethodMetadata{2, &CxxCalculatorModule::divide};
  methodMap_["multiply"] = MethodMetadata{2, &CxxCalculatorModule::multiply};
  methodMap_["subtract"] = MethodMetadata{2, &CxxCalculatorModule::subtract};
}

CxxCalculatorModule::~CxxCalculatorModule() {
  invalidate();
}

void CxxCalculatorModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxCalculatorModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabytest::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabytest::utils::errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabytest::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabytest::utils::errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabytest::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabytest::utils::errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::crabytest::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::crabytest::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace crabytest
} // namespace craby
